// All site copy, in both languages. Edit here, then run `node build.mjs`.
// Facts come from the CV (assets/docs) and the KYH degree certificate.

export const site = {
  name: 'Mark Walusimbi',
  url: 'https://markarnold03.github.io/',
  email: 'markanorld0@gmail.com',
  linkedin: 'https://linkedin.com/in/mark-walusimbi',
  github: 'https://github.com/MarkArnold03',
  cv: 'assets/docs/CV_Mark_Walusimbi.pdf',
};

// Degree courses: [swedish name, english name, credits, grade]
const courses = [
  ['Objektorienterad programmering C#', 'Object-oriented programming in C#', 60, 'G'],
  ['HTML5, CSS3 och JavaScript', 'HTML5, CSS3 and JavaScript', 40, 'VG'],
  ['Webbutveckling .NET', 'Web development in .NET', 40, 'G'],
  ['Systemutveckling i .NET', 'Systems development in .NET', 40, 'G'],
  ['Agila arbetsmetoder', 'Agile methods', 40, 'G'],
  ['Databasteknik', 'Database technology', 30, 'G'],
  ['Testning', 'Testing', 20, 'G'],
  ['Projekt 1', 'Project 1', 10, 'G'],
  ['Projekt 2', 'Project 2', 10, 'G'],
  ['LIA 1', 'Internship 1 (LIA)', 50, 'VG'],
  ['LIA 2', 'Internship 2 (LIA)', 50, 'VG'],
  ['Examensarbete', 'Degree project', 30, 'G'],
  ['Medarbetarskap och branschkunskap', 'Teamwork and industry knowledge', 5, 'G'],
  ['Jämlikhet i yrkeslivet', 'Equality in working life', 5, 'VG'],
];

// Route map: slot = position along the line, lane = 'code' | 'floor' | 'junction' | 'next'
const stops = [
  { slot: 0, lane: 'code', year: '2019', name: 'Fyrisskolan' },
  { slot: 1, lane: 'code', year: '2022', name: 'KYH' },
  { slot: 1, lane: 'floor', year: '2022', name: 'Kulturarenor' },
  { slot: 2, lane: 'floor', year: '2023', name: 'DHL Arlanda' },
  { slot: 3, lane: 'code', year: '2024', name: 'RedRiver' },
  { slot: 3, lane: 'floor', year: '2024', name: 'Svea Takvård' },
  { slot: 4, lane: 'floor', year: '2025', name: 'Future Mobility' },
  { slot: 5, lane: 'junction', year: '2025', name: 'LAPX AB' },
];

const en = {
  lang: 'en', other: 'sv', path: '', otherPath: 'sv/', otherLabel: 'SV', otherName: 'Svenska',
  title: 'Mark Walusimbi — fullstack developer, Stockholm',
  description: 'Fullstack .NET and JavaScript developer in Stockholm. From the warehouse floor to production: projects, route, skills and degree.',
  skip: 'Skip to content',
  logoSub: 'Fullstack · .NET · JS',
  navLabel: 'Sections',
  nav: [['board', 'Board'], ['track', 'Track'], ['route', 'Route'], ['manifest', 'Manifest'], ['docs', 'Customs'], ['pickup', 'Pickup']],
  clockLabel: 'Stockholm time',
  shift: { day: 'Day shift', night: 'Night shift', toDay: 'Switch to day shift', toNight: 'Switch to night shift' },
  ticker: ['Open to work', 'Stockholm & remote', '.NET 9 · C# · JavaScript', '~100 daily users in production', '450+ xUnit tests', '9 languages in the field app', '~90 API controllers', 'Driving licence B'],
  tickerLabel: 'Status',

  hero: {
    dock: 'Dock 01 — Departures · Stockholm',
    title: ['From the', 'warehouse floor', 'to production.'],
    lede: "I'm a fullstack .NET and JavaScript developer. I've worked the warehouse floor and driven the deliveries. Then I built the platform a logistics company runs on: backend, frontend, integrations and the app in the driver's pocket.",
    ctaTrack: 'Track my work', ctaPickup: 'Book a pickup', ctaCv: 'Download CV',
  },
  board: {
    label: 'Departures board', head: 'Departures', cols: ['Year', 'Destination', 'Via', 'Status'],
    hint: 'Select a departure to track it',
  },
  status: { delivered: 'Delivered', live: 'Live', boarding: 'Boarding' },
  statusAlt: 'Available',

  track: {
    dock: 'Dock 02 — Tracking',
    title: 'Track a shipment.',
    lede: 'Every project is a shipment. Enter a tracking number, or pick one below.',
    field: 'Tracking number', placeholder: 'e.g. MW-LAPX-25', button: 'Track', key: 'to track',
    chips: 'Shipments', notFound: 'No shipment matches “{q}”. Try MW-LAPX-25.',
    events: 'Scan events', contents: 'Contents', from: 'From', to: 'To', number: 'Tracking no.',
  },
  shipments: [
    {
      code: 'MW-LAPX-25', board: ['2025', 'LAPX PLATFORM', '.NET 9 · JS'], title: 'LAPX platform', status: 'delivered',
      from: 'Database', to: "Driver's pocket",
      meta: [['Service', 'Fullstack developer'], ['Period', '06/2025 – 06/2026'], ['Users', '~100 staff, every day'], ['Place', 'LAPX AB, Stockholm']],
      events: [
        ['06/2026', 'Delivered', 'In daily production use by around 100 people in transport, moving, warehouse and assembly.'],
        ['', 'Releases', 'Owned the release chain: build, versioning, verified IIS deploys, rollback and production troubleshooting. Grew the xUnit suite to 450+ tests.'],
        ['', 'Field app', 'A PWA for drivers, warehouse staff and installers: clock in and out with GPS geofence, offline queue in IndexedDB, QR scanning, damage reports with photos, 9 languages.'],
        ['', 'Frontend', 'JavaScript SPA for staffing, dispatch, live map, warehouse and time reporting, plus an in-app AI assistant on the Claude API.'],
        ['', 'Real-time', 'SignalR and Server-Sent Events for staffing, attendance, shifts and permission changes.'],
        ['', 'Time & HR', 'Working hours with automatic breaks, overtime approval, comp-time balance, absence and Excel export.'],
        ['', 'Integrations', 'Background services for Opter TMS, Ongoing WMS (API and webhooks), Movex, Business Central and Keatech vehicle GPS. Leads fetched and parsed from email via Microsoft Graph and IMAP.'],
        ['', 'Access', 'A four-level role model with JWT and refresh tokens, permissions per module and audit logging.'],
        ['', 'Backend', 'Business-critical backend in .NET 9, ASP.NET Core Web API, Clean Architecture, EF Core and SQL Server, with about 90 API controllers.'],
        ['06/2025', 'Picked up', 'Joined LAPX AB in Stockholm as fullstack developer.'],
      ],
      contents: ['C#', '.NET 9', 'ASP.NET Core', 'EF Core', 'SQL Server', 'SignalR', 'SSE', 'JavaScript', 'PWA', 'IndexedDB', 'IIS', 'xUnit', 'Claude API'],
      note: 'Code and screenshots belong to LAPX and stay private. Happy to walk you through it in an interview.',
    },
    {
      code: 'MW-KYH-24', board: ['2024', 'KYH DEGREE', '430 YH CREDITS'], title: '.NET developer degree', status: 'delivered',
      from: 'KYH, 2022', to: 'Degree, 2024',
      meta: [['Service', 'Yrkeshögskoleexamen, .NET Developer'], ['Period', '08/2022 – 08/2024'], ['Scope', '430 YH credits'], ['Result', 'Every course passed, 4 with distinction']],
      events: [
        ['08/2024', 'Delivered', 'Programme completed with a pass in every course.'],
        ['08/2024', 'Internship', 'Internship courses LIA 1 and LIA 2 (100 credits), both passed with distinction.'],
        ['06/2024', 'Degree project', 'Degree project (examensarbete) passed.'],
        ['2023', 'Core', 'Object-oriented C#, web and systems development in .NET, agile methods, databases and testing.'],
        ['04/2023', 'Web', 'HTML5, CSS3 and JavaScript, passed with distinction.'],
        ['08/2022', 'Picked up', 'Started the two-year .NET developer programme at KYH in Stockholm.'],
      ],
      contents: ['C#', '.NET', 'ASP.NET Core', 'SQL', 'HTML5', 'CSS3', 'JavaScript', 'Testing', 'Agile'],
      links: [['#docs', 'Degree and all grades']],
    },
    {
      code: 'MW-RDRV-24', board: ['2024', 'REDRIVER', '.NET · ANGULAR'], title: 'RedRiver internship', status: 'delivered',
      from: 'Classroom', to: 'Production code',
      meta: [['Service', 'Backend/.NET developer, intern'], ['Period', '02/2024 – 08/2024'], ['Place', 'RedRiver Consulting and Software, Stockholm']],
      events: [
        ['08/2024', 'Delivered', 'Internship completed.'],
        ['', 'AI', 'Built a project on the OpenAI API that analysed candidate profiles and matched them to job listings.'],
        ['', 'Frontend', 'Worked on the frontend in Angular and TypeScript.'],
        ['', 'Backend', 'Developed and maintained business-critical systems in .NET and built RESTful APIs for web applications.'],
        ['02/2024', 'Picked up', 'Started as backend/.NET intern.'],
      ],
      contents: ['C#', '.NET', 'REST', 'Angular', 'TypeScript', 'OpenAI API'],
    },
    {
      code: 'MW-BANK-23', board: ['2023', 'BANKWEBAPP', 'ASP.NET MVC'], title: 'BankWebApp', status: 'delivered',
      from: 'Empty repo', to: 'Working bank',
      meta: [['Service', 'Solo developer'], ['Period', '04/2023 – 06/2023'], ['Place', 'School project, KYH']],
      events: [
        ['06/2023', 'Delivered', 'Finished. The full source is public on GitHub.'],
        ['', 'Data', 'Entity Framework Core on SQL Server.'],
        ['', 'Transactions', 'Transaction handling, with account history loaded over AJAX so pages stay fast.'],
        ['', 'Customers', 'Paginated customer search across the whole register.'],
        ['', 'Roles', 'ASP.NET Core Identity with separate admin and cashier roles.'],
        ['04/2023', 'Picked up', "Started on the core of a bank's internal system."],
      ],
      contents: ['C#', 'ASP.NET Core MVC', 'EF Core', 'Identity', 'SQL Server', 'AJAX'],
      links: [['https://github.com/MarkArnold03/BankWebApp', 'Source on GitHub']],
    },
    {
      code: 'MW-RROCK', board: ['----', 'RISING ROCK', 'WEB'], title: 'Rising Rock', status: 'live',
      from: 'Blank page', to: 'risingrock.se',
      meta: [['Service', 'Designer and developer'], ['Client', 'Rising Rock, a web design studio'], ['Type', 'Website']],
      events: [
        ['', 'Live', 'Online at risingrock.se.'],
        ['', 'Built', 'Designed and built the whole site, from layout to launch.'],
        ['', 'Brief', 'Explain the offer simply: see a finished demo first, and only pay if you like it.'],
        ['', 'Picked up', 'A small studio run by a friend, building websites for local businesses, needed its own site.'],
      ],
      contents: ['Design', 'HTML', 'CSS', 'JavaScript'],
      links: [['https://risingrock.se', 'Visit risingrock.se']],
    },
    {
      code: 'MW-NEXT-26', board: ['NOW', 'YOUR TEAM', 'C# · .NET · JS'], title: 'Your team', status: 'boarding',
      from: 'Stockholm', to: 'Your team',
      meta: [['Service', 'Fullstack developer, .NET / C# / JavaScript'], ['Available', 'Now'], ['Where', 'Stockholm or remote'], ['Licence', 'B, own car']],
      events: [
        ['Now', 'Awaiting pickup', 'Open to developer roles in Stockholm and remote.'],
        ['', 'Ready', 'Used to owning the whole chain, from data model and API to integrations, tests and deploys, and to working directly with the business.'],
      ],
      contents: ['Backend', 'Frontend', 'Integrations', 'Tests', 'Deploys', 'AI-assisted development'],
      links: [['#pickup', 'Book a pickup']],
    },
  ],

  route: {
    dock: 'Dock 03 — Route map',
    title: 'Two lines, one junction.',
    lede: 'For years I rode two lines at once: code, and the warehouse floor. At LAPX they met, and I built software for the kind of work I used to do by hand.',
    label: 'Career route map: the code line and the floor line meet at LAPX AB in 2025, and continue together towards your team.',
    code: 'Code line', floor: 'Floor line', both: 'Both lines', next: 'Your team?', swipe: 'Swipe the map',
    timetable: 'Timetable', cols: ['Year', 'Line', 'Stop', 'Notes'],
    rows: [
      ['2025 – 2026', 'junction', 'LAPX AB', 'Fullstack developer. Where logistics know-how and code met.'],
      ['2025', 'floor', 'Future Mobility', 'Customer deliveries, moving help, furniture assembly and warehouse work.'],
      ['2024', 'floor', 'Svea Takvård', 'Seasonal roof maintenance and selling add-on services.'],
      ['2024', 'code', 'RedRiver', 'Backend/.NET intern.'],
      ['2023 – 2024', 'floor', 'DHL Arlanda', 'Warehouse: inventory, logistics and supplier contacts.'],
      ['2022 – 2024', 'floor', 'Kulturarenor', 'Barback and bartender. High-tempo service and events.'],
      ['2022 – 2024', 'code', 'KYH', '.NET developer programme, Stockholm.'],
      ['2019 – 2022', 'code', 'Fyrisskolan', 'Teknikprogrammet, Uppsala. Programming 1 and 2 in C# and web development.'],
    ],
  },

  manifest: {
    dock: 'Dock 04 — Manifest',
    title: "What's in the load.",
    lede: 'Everything here is on my CV. Packed by crate, no fake skill bars.',
    crate: 'Crate', qty: 'Qty',
  },
  crates: [
    ['Backend', ['C#', '.NET 9', 'ASP.NET Core', 'Web API', 'REST', 'Entity Framework Core', 'Clean Architecture', 'SignalR', 'Server-Sent Events', 'Background services', 'JWT authentication', 'OpenAPI / Swagger', 'Serilog', 'Node.js']],
    ['Frontend', ['JavaScript (ES6+)', 'TypeScript', 'HTML5', 'CSS', 'SPA', 'PWA', 'Service workers', 'IndexedDB', 'i18n', 'Angular', 'React', 'Tailwind CSS', 'esbuild']],
    ['Data', ['SQL Server', 'T-SQL', 'MySQL', 'Relational modelling', 'Database design']],
    ['Integrations', ['Opter TMS', 'Ongoing WMS', 'Movex', 'Business Central', 'Microsoft Graph', 'MSAL', 'IMAP / SMTP', 'Webhooks', 'Excel import & export']],
    ['Test & DevOps', ['xUnit', 'NUnit', 'Moq', 'Postman', 'IIS', 'CI/CD', 'Azure DevOps', 'Git', 'GitHub', 'PowerShell']],
    ['AI', ['Claude Code, daily', 'Claude API', 'OpenAI API']],
    ['Ways of working', ['Agile', 'Scrum', 'Kanban', 'Jira', 'Trello', 'Requirements with the business']],
    ['Languages & licence', ['English, native', 'Luganda, native', 'Swedish, fluent (C1)', 'Driving licence B, own car']],
  ],

  docs: {
    dock: 'Dock 05 — Customs',
    title: 'Papers in order.',
    lede: 'The degree and the CV, ready for inspection.',
    certHead: 'Certificate of origin', certKind: 'Higher vocational degree',
    certFields: [['Holder', 'Mark Walusimbi'], ['Qualification', 'Yrkeshögskoleexamen, .NET Developer'], ['Issuer', 'KYH, Stockholm'], ['Scope', '430 YH credits (about 86 weeks full time)'], ['Completed', '1 August 2024'], ['Result', 'Every course passed, 4 with distinction']],
    stamp: ['Passed', '430 YH', 'KYH 2024'],
    courses: 'All 14 courses and grades', courseCols: ['Course', 'Credits', 'Grade'], total: 'Total',
    grade: { G: 'Pass', VG: 'Distinction' },
    gradeNote: 'Graded Fail, Pass (G) or Pass with distinction (VG). Five YH credits equal one week of full-time study.',
    onRequest: 'The original, digitally signed certificate is available on request.',
    cvHead: 'Cargo manifest', cvKind: 'Curriculum vitae',
    cvFields: [['Format', 'PDF, 2 pages'], ['Language', 'Swedish'], ['Contents', 'Profile, skills, experience, education, projects']],
    cvButton: 'Download CV',
  },

  pickup: {
    dock: 'Dock 06 — Pickup',
    title: 'Book a pickup.',
    lede: "Open to developer roles in Stockholm and remote. Tell me what you're shipping.",
    lines: 'Direct lines', email: 'Email', copy: 'Copy', copied: 'Email address copied',
    form: 'Booking', company: 'Company', companyPh: 'Where would I work?', role: 'Role', rolePh: 'e.g. .NET developer',
    message: 'Message', messagePh: 'A few words about the team and the work',
    submit: 'Create booking email', formNote: "Opens your email app with the booking filled in. This site doesn't send or store anything.",
    subject: 'Pickup booking: {role} at {company}', body: 'Hi Mark,\n\n{message}\n\n{company}',
    fallbackRole: 'developer role', fallbackCompany: 'our company',
  },

  footer: {
    from: 'From', fromVal: 'Mark Walusimbi\nStockholm, SE', to: 'To', toVal: 'You, hopefully', service: 'Service', serviceVal: 'Fullstack · Express',
    built: 'Hand-built with HTML, CSS and JavaScript. No cookies, no trackers.',
  },

  notFound: { title: 'Return to sender.', text: 'Parcel 404: there is no delivery point at this address.', home: 'Back to the terminal' },
};

const sv = {
  lang: 'sv', other: 'en', path: 'sv/', otherPath: '', otherLabel: 'EN', otherName: 'English',
  title: 'Mark Walusimbi — fullstack-utvecklare, Stockholm',
  description: 'Fullstack-utvecklare inom .NET och JavaScript i Stockholm. Från lagergolvet till produktion: projekt, rutt, kompetens och examen.',
  skip: 'Hoppa till innehållet',
  logoSub: 'Fullstack · .NET · JS',
  navLabel: 'Sektioner',
  nav: [['board', 'Tavla'], ['track', 'Spåra'], ['route', 'Rutt'], ['manifest', 'Last'], ['docs', 'Tull'], ['pickup', 'Hämtning']],
  clockLabel: 'Tid i Stockholm',
  shift: { day: 'Dagskift', night: 'Nattskift', toDay: 'Byt till dagskift', toNight: 'Byt till nattskift' },
  ticker: ['Öppen för jobb', 'Stockholm & distans', '.NET 9 · C# · JavaScript', '~100 dagliga användare i produktion', '450+ xUnit-tester', '9 språk i fältappen', '~90 API-controllers', 'B-körkort'],
  tickerLabel: 'Status',

  hero: {
    dock: 'Docka 01 — Avgångar · Stockholm',
    title: ['Från', 'lagergolvet', 'till produktion.'],
    lede: 'Jag är fullstack-utvecklare inom .NET och JavaScript. Jag har jobbat på lagergolvet och kört leveranserna. Sedan byggde jag plattformen som ett logistikföretag drivs på: backend, frontend, integrationer och appen i förarens ficka.',
    ctaTrack: 'Spåra mitt arbete', ctaPickup: 'Boka upphämtning', ctaCv: 'Ladda ner CV',
  },
  board: {
    label: 'Avgångstavla', head: 'Avgångar', cols: ['År', 'Destination', 'Via', 'Status'],
    hint: 'Välj en avgång för att spåra den',
  },
  status: { delivered: 'Levererad', live: 'Live', boarding: 'Påstigning' },
  statusAlt: 'Redo nu',

  track: {
    dock: 'Docka 02 — Spårning',
    title: 'Spåra en försändelse.',
    lede: 'Varje projekt är en försändelse. Skriv ett spårningsnummer eller välj ett nedan.',
    field: 'Spårningsnummer', placeholder: 't.ex. MW-LAPX-25', button: 'Spåra', key: 'för att spåra',
    chips: 'Försändelser', notFound: 'Ingen försändelse matchar ”{q}”. Prova MW-LAPX-25.',
    events: 'Skanningshändelser', contents: 'Innehåll', from: 'Från', to: 'Till', number: 'Spårningsnr',
  },
  shipments: [
    {
      code: 'MW-LAPX-25', board: ['2025', 'LAPX-PLATTFORM', '.NET 9 · JS'], title: 'LAPX-plattformen', status: 'delivered',
      from: 'Databasen', to: 'Förarens ficka',
      meta: [['Tjänst', 'Fullstack-utvecklare'], ['Period', '06/2025 – 06/2026'], ['Användare', '~100 anställda, varje dag'], ['Plats', 'LAPX AB, Stockholm']],
      events: [
        ['06/2026', 'Levererad', 'Används dagligen i produktion av ett hundratal personer inom transport, flytt, lager och montering.'],
        ['', 'Releaser', 'Ansvarade för release-kedjan: bygg, versionshantering, verifierad deploy i IIS, rollback och felsökning i produktion. Utökade testsviten i xUnit till över 450 tester.'],
        ['', 'Fältapp', 'En PWA för förare, lagerpersonal och montörer: in- och utstämpling med GPS-geofence, offlinekö i IndexedDB, QR-skanning, skaderapporter med foton och stöd för 9 språk.'],
        ['', 'Frontend', 'SPA i JavaScript för bemanningsplanering, dispatch, livekarta, lager och tidrapportering, samt en AI-assistent i appen kopplad till Claude API.'],
        ['', 'Realtid', 'SignalR och Server-Sent Events för bemanning, närvaro, pass och behörighetsändringar.'],
        ['', 'Tid & HR', 'Arbetstid med automatiska raster, attest av övertid, kompsaldo, frånvaro och Excel-export.'],
        ['', 'Integrationer', 'Bakgrundstjänster mot Opter TMS, Ongoing WMS (API och webhooks), Movex, Business Central och Keatech fordons-GPS. Leads hämtas och tolkas automatiskt från e-post via Microsoft Graph och IMAP.'],
        ['', 'Behörighet', 'En rollbaserad behörighetsmodell i fyra nivåer med JWT och refresh tokens, behörighet per modul och audit logging.'],
        ['', 'Backend', 'Affärskritisk backend i .NET 9, ASP.NET Core Web API, Clean Architecture, EF Core och SQL Server, med ett nittiotal API-controllers.'],
        ['06/2025', 'Upphämtad', 'Började som fullstack-utvecklare på LAPX AB i Stockholm.'],
      ],
      contents: ['C#', '.NET 9', 'ASP.NET Core', 'EF Core', 'SQL Server', 'SignalR', 'SSE', 'JavaScript', 'PWA', 'IndexedDB', 'IIS', 'xUnit', 'Claude API'],
      note: 'Kod och skärmbilder tillhör LAPX och förblir privata. Jag visar gärna hur det fungerar på en intervju.',
    },
    {
      code: 'MW-KYH-24', board: ['2024', 'KYH-EXAMEN', '430 YH-POÄNG'], title: '.NET-utvecklare, examen', status: 'delivered',
      from: 'KYH, 2022', to: 'Examen, 2024',
      meta: [['Tjänst', 'Yrkeshögskoleexamen, .NET Developer'], ['Period', '08/2022 – 08/2024'], ['Omfattning', '430 YH-poäng'], ['Resultat', 'Godkänd i alla kurser, 4 med VG']],
      events: [
        ['08/2024', 'Levererad', 'Utbildningen slutförd med godkänt i alla kurser.'],
        ['08/2024', 'LIA', 'Praktikkurserna LIA 1 och LIA 2 (100 poäng), båda med väl godkänt.'],
        ['06/2024', 'Examensarbete', 'Examensarbetet godkänt.'],
        ['2023', 'Kärnan', 'Objektorienterad C#, webb- och systemutveckling i .NET, agila arbetsmetoder, databaser och testning.'],
        ['04/2023', 'Webb', 'HTML5, CSS3 och JavaScript, väl godkänt.'],
        ['08/2022', 'Upphämtad', 'Började den tvååriga utbildningen till .NET-utvecklare på KYH i Stockholm.'],
      ],
      contents: ['C#', '.NET', 'ASP.NET Core', 'SQL', 'HTML5', 'CSS3', 'JavaScript', 'Testning', 'Agilt'],
      links: [['#docs', 'Examen och alla betyg']],
    },
    {
      code: 'MW-RDRV-24', board: ['2024', 'REDRIVER', '.NET · ANGULAR'], title: 'Praktik på RedRiver', status: 'delivered',
      from: 'Klassrummet', to: 'Produktionskod',
      meta: [['Tjänst', 'Backend-/.NET-utvecklare, praktik'], ['Period', '02/2024 – 08/2024'], ['Plats', 'RedRiver Consulting and Software, Stockholm']],
      events: [
        ['08/2024', 'Levererad', 'Praktiken avslutad.'],
        ['', 'AI', 'Byggde ett projekt mot OpenAI:s API som analyserade kandidatprofiler och matchade dem mot platsannonser.'],
        ['', 'Frontend', 'Arbetade med frontend i Angular och TypeScript.'],
        ['', 'Backend', 'Utvecklade och underhöll affärskritiska system i .NET och byggde RESTful API:er för webbapplikationer.'],
        ['02/2024', 'Upphämtad', 'Började som praktikant inom backend/.NET.'],
      ],
      contents: ['C#', '.NET', 'REST', 'Angular', 'TypeScript', 'OpenAI API'],
    },
    {
      code: 'MW-BANK-23', board: ['2023', 'BANKWEBAPP', 'ASP.NET MVC'], title: 'BankWebApp', status: 'delivered',
      from: 'Tomt repo', to: 'Fungerande bank',
      meta: [['Tjänst', 'Ensam utvecklare'], ['Period', '04/2023 – 06/2023'], ['Plats', 'Skolprojekt, KYH']],
      events: [
        ['06/2023', 'Levererad', 'Klart. Hela källkoden finns öppet på GitHub.'],
        ['', 'Data', 'Entity Framework Core mot SQL Server.'],
        ['', 'Transaktioner', 'Transaktionshantering, där kontohistoriken laddas med AJAX så att sidorna går snabbt.'],
        ['', 'Kunder', 'Kundsök med paginering i hela registret.'],
        ['', 'Roller', 'ASP.NET Core Identity med separata roller för admin och kassör.'],
        ['04/2023', 'Upphämtad', 'Började bygga kärnan i en banks interna system.'],
      ],
      contents: ['C#', 'ASP.NET Core MVC', 'EF Core', 'Identity', 'SQL Server', 'AJAX'],
      links: [['https://github.com/MarkArnold03/BankWebApp', 'Källkoden på GitHub']],
    },
    {
      code: 'MW-RROCK', board: ['----', 'RISING ROCK', 'WEBB'], title: 'Rising Rock', status: 'live',
      from: 'Tom sida', to: 'risingrock.se',
      meta: [['Tjänst', 'Designer och utvecklare'], ['Kund', 'Rising Rock, en webbyrå'], ['Typ', 'Webbplats']],
      events: [
        ['', 'Live', 'Online på risingrock.se.'],
        ['', 'Byggd', 'Designade och byggde hela sajten, från layout till lansering.'],
        ['', 'Uppdrag', 'Förklara erbjudandet enkelt: se en färdig demo först, och betala bara om du gillar den.'],
        ['', 'Upphämtad', 'En liten byrå som drivs av en vän och bygger webbplatser åt lokala företag behövde en egen sajt.'],
      ],
      contents: ['Design', 'HTML', 'CSS', 'JavaScript'],
      links: [['https://risingrock.se', 'Besök risingrock.se']],
    },
    {
      code: 'MW-NEXT-26', board: ['NU', 'DITT TEAM', 'C# · .NET · JS'], title: 'Ditt team', status: 'boarding',
      from: 'Stockholm', to: 'Ditt team',
      meta: [['Tjänst', 'Fullstack-utvecklare, .NET / C# / JavaScript'], ['Tillgänglig', 'Nu'], ['Var', 'Stockholm eller distans'], ['Körkort', 'B, egen bil']],
      events: [
        ['Nu', 'Väntar på upphämtning', 'Öppen för utvecklarroller i Stockholm och på distans.'],
        ['', 'Redo', 'Van att äga hela kedjan, från datamodell och API till integrationer, tester och deploy, och att kravställa direkt mot verksamheten.'],
      ],
      contents: ['Backend', 'Frontend', 'Integrationer', 'Tester', 'Deploy', 'AI-assisterad utveckling'],
      links: [['#pickup', 'Boka upphämtning']],
    },
  ],

  route: {
    dock: 'Docka 03 — Linjekarta',
    title: 'Två linjer, en knutpunkt.',
    lede: 'I flera år åkte jag på två linjer samtidigt: kod och lagergolvet. På LAPX möttes de, och jag byggde mjukvara för den sortens jobb jag tidigare gjort för hand.',
    label: 'Linjekarta över min karriär: kodlinjen och golvlinjen möts på LAPX AB 2025 och fortsätter tillsammans mot ditt team.',
    code: 'Kodlinjen', floor: 'Golvlinjen', both: 'Båda linjerna', next: 'Ditt team?', swipe: 'Svep kartan',
    timetable: 'Tidtabell', cols: ['År', 'Linje', 'Hållplats', 'Anteckning'],
    rows: [
      ['2025 – 2026', 'junction', 'LAPX AB', 'Fullstack-utvecklare. Där logistikkunskap och kod möttes.'],
      ['2025', 'floor', 'Future Mobility', 'Kundleveranser, flytthjälp, möbelmontering och lagerhantering.'],
      ['2024', 'floor', 'Svea Takvård', 'Takunderhåll och merförsäljning av tilläggstjänster, säsong.'],
      ['2024', 'code', 'RedRiver', 'Praktikant inom backend/.NET.'],
      ['2023 – 2024', 'floor', 'DHL Arlanda', 'Lager: inventering, logistik och leverantörskontakter.'],
      ['2022 – 2024', 'floor', 'Kulturarenor', 'Barback och bartender. Service och event i högt tempo.'],
      ['2022 – 2024', 'code', 'KYH', 'Utbildning till .NET-utvecklare, Stockholm.'],
      ['2019 – 2022', 'code', 'Fyrisskolan', 'Teknikprogrammet, Uppsala. Programmering 1 och 2 i C# och webbutveckling.'],
    ],
  },

  manifest: {
    dock: 'Docka 04 — Lastlista',
    title: 'Det här finns i lasten.',
    lede: 'Allt här står i mitt CV. Packat i lådor, utan påhittade kunskapsstaplar.',
    crate: 'Låda', qty: 'Ant',
  },
  crates: [
    ['Backend', ['C#', '.NET 9', 'ASP.NET Core', 'Web API', 'REST', 'Entity Framework Core', 'Clean Architecture', 'SignalR', 'Server-Sent Events', 'Bakgrundstjänster', 'JWT-autentisering', 'OpenAPI / Swagger', 'Serilog', 'Node.js']],
    ['Frontend', ['JavaScript (ES6+)', 'TypeScript', 'HTML5', 'CSS', 'SPA', 'PWA', 'Service workers', 'IndexedDB', 'i18n', 'Angular', 'React', 'Tailwind CSS', 'esbuild']],
    ['Data', ['SQL Server', 'T-SQL', 'MySQL', 'Relationsmodellering', 'Databasdesign']],
    ['Integrationer', ['Opter TMS', 'Ongoing WMS', 'Movex', 'Business Central', 'Microsoft Graph', 'MSAL', 'IMAP / SMTP', 'Webhooks', 'Excel-import och -export']],
    ['Test & DevOps', ['xUnit', 'NUnit', 'Moq', 'Postman', 'IIS', 'CI/CD', 'Azure DevOps', 'Git', 'GitHub', 'PowerShell']],
    ['AI', ['Claude Code, dagligen', 'Claude API', 'OpenAI API']],
    ['Arbetssätt', ['Agilt', 'Scrum', 'Kanban', 'Jira', 'Trello', 'Kravställning mot verksamheten']],
    ['Språk & körkort', ['Engelska, modersmål', 'Luganda, modersmål', 'Svenska, flytande (C1)', 'B-körkort, egen bil']],
  ],

  docs: {
    dock: 'Docka 05 — Tull',
    title: 'Papperen i ordning.',
    lede: 'Examen och CV, redo för granskning.',
    certHead: 'Ursprungsintyg', certKind: 'Yrkeshögskoleexamen',
    certFields: [['Innehavare', 'Mark Walusimbi'], ['Examen', 'Yrkeshögskoleexamen, .NET Developer'], ['Utfärdare', 'KYH, Stockholm'], ['Omfattning', '430 YH-poäng (cirka 86 veckors heltidsstudier)'], ['Slutförd', '1 augusti 2024'], ['Resultat', 'Godkänd i alla kurser, 4 med VG']],
    stamp: ['Godkänd', '430 YH', 'KYH 2024'],
    courses: 'Alla 14 kurser och betyg', courseCols: ['Kurs', 'YH-poäng', 'Betyg'], total: 'Summa',
    grade: { G: 'Godkänt', VG: 'Väl godkänt' },
    gradeNote: 'Betygen är Icke godkänt, Godkänt (G) eller Väl godkänt (VG). Fem YH-poäng motsvarar en veckas heltidsstudier.',
    onRequest: 'Det digitalt signerade examensbeviset visas gärna på begäran.',
    cvHead: 'Fraktsedel', cvKind: 'Curriculum vitae',
    cvFields: [['Format', 'PDF, 2 sidor'], ['Språk', 'Svenska'], ['Innehåll', 'Profil, kompetens, erfarenhet, utbildning, projekt']],
    cvButton: 'Ladda ner CV',
  },

  pickup: {
    dock: 'Docka 06 — Upphämtning',
    title: 'Boka en upphämtning.',
    lede: 'Öppen för utvecklarroller i Stockholm och på distans. Berätta vad ni ska skicka.',
    lines: 'Direktlinjer', email: 'E-post', copy: 'Kopiera', copied: 'E-postadressen kopierad',
    form: 'Bokning', company: 'Företag', companyPh: 'Var skulle jag jobba?', role: 'Roll', rolePh: 't.ex. .NET-utvecklare',
    message: 'Meddelande', messagePh: 'Några ord om teamet och jobbet',
    submit: 'Skapa bokningsmejl', formNote: 'Öppnar din e-postapp med bokningen ifylld. Sajten skickar eller sparar ingenting.',
    subject: 'Bokning: {role} hos {company}', body: 'Hej Mark,\n\n{message}\n\n{company}',
    fallbackRole: 'utvecklarroll', fallbackCompany: 'vårt företag',
  },

  footer: {
    from: 'Från', fromVal: 'Mark Walusimbi\nStockholm, SE', to: 'Till', toVal: 'Du, förhoppningsvis', service: 'Tjänst', serviceVal: 'Fullstack · Express',
    built: 'Handbyggd med HTML, CSS och JavaScript. Inga cookies, inga spårare.',
  },

  notFound: { title: 'Åter till avsändaren.', text: 'Paket 404: det finns ingen leveranspunkt på den här adressen.', home: 'Tillbaka till terminalen' },
};

export const langs = { en, sv };
export { courses, stops };
